FROM runpod/pytorch:1.0.2-cu1281-torch280-ubuntu2404

WORKDIR /app

RUN pip install runpod hf_transfer xfuser==0.4.5 --no-deps

COPY serverless-test/handler.py .

ENTRYPOINT []

CMD ["python", "handler.py"]
